[package]
name = "mala-idea"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
axum-server = { version = "0.7", features = ["tls-rustls"] }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pki-types = "1.10"
tower = "0.5"
futures-util = "0.3"
x509-parser = "0.16"
