[package]
name = "servidor-autenticacion-dnie"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
axum-server = { version = "0.7", features = ["tls-rustls"] }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }
rustls = "0.23"
env_logger = "0.11"
rustls-pki-types = "1.10"
rustls-webpki = { version = "0.102", features = ["aws_lc_rs"], default-features = false }
