[package]
name = "mala-idea"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-rustls = "0.26.1"
rustls = "0.23.20"
rustls-pki-types = "1.10.1"
tower = "0.5.2"
futures-util = "0.3.31"
x509-parser = "0.16.0"
